version: "3"

services:
  python:
    build:
      context: .
    container_name: ${APP_NAME}_python_container
    volumes:
      - .:/app
    ports:
      - "1200:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: tail -f /dev/null
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}_postgres_container
    restart: unless-stopped
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
